### PR TITLE
Update documentation for docker-compose

### PR DESCRIPTION
**Pull request by eschizoid**

### CODE REVIEW

**Comment by sarkonovich** [comment]
Mariano,

Thanks for the work on the Docker build. I haven't tried to install it myself yet, but I will over the next couple days. 

What are the advantages of docker Compose?

**Comment by eschizoid** [comment]
@sarkonovich just one command instead of having to execute 2... IMHO is a more cleaner way for linking docker containers. Feel free to try it, I just finished testing the one for raspberry pi's and works great 😉 

EDIT:
More here:
https://docs.docker.com/compose/

**Comment by sarkonovich** [comment]
How do we set the timezone?  That seems to be hardcoded in the yml.

I think I'm inclined to stick with other method. Mostly because I'm not Docker expert, and I end up trouble shooting installs for people a lot! The fewer things I need to learn the better. Learning isn't my strong suit :) 

I can take care of the typo in your docker hub address.

**Comment by eschizoid** [comment]
I can pass that as parameter if you want me to, just trying to make everybody else life easier.

Again, thanks for you great work!

**Comment by sarkonovich** [comment]
Okay, let me look at the info you gave me. For now, I fixed the address to your Docker Hub, so it would be cleaner if you sent in a new pull request, maybe passing along the TZ info as a parameter.

Thanks for your help on this.

**Comment by eschizoid** [comment]
Sounds good, I will do it.

Just one more thing, the ngrok container address also needs to be updated: `eschizoid/docker-ngrok-armhf`

**Comment by eschizoid** [comment]
@sarkonovich you almost got it right, you have `eschizoid/ngrok-armhf` and should be `eschizoid/docker-ngrok-armhf` (just missing the docker part)

**Pull request closed without merging**
